kubernetes-sigs/provider-aws-test-infra

OWNERS
Adding myself to OWNERS to help use this repository for some testing stuff related to AWS
Also see this repo where we have a test-e2e-node that works with AWS
- https://github.com/dims/remote-aws-runner 
and possibly some stuff from:
- https://github.com/aws/aws-k8s-tester
=> Update OWNERS - Add `dims`

hack/make-rules/test-e2e-node.sh
=> Allow access to SSH

hack/make-rules/test-e2e-node.sh
Same as the PR in k/k:
https://github.com/kubernetes/kubernetes/pull/118567
=> Prep for arm64 based ci jobs

config/aws-instance-arm64.yaml
=> Pick suitable instance type for arm64

config/configure.sh
as ubuntu arm64 doesn't seem to have it.
=> Drop dependency on "jq"

config/configure.sh
we do this elsewhere as well:
https://github.com/search?q=repo%3Akubernetes%2Fk8s.io%20fs.inotify.max_user_watches&type=code
=> Tweak inotify settings

config/aws-instance-arm64.yaml, config/configure.sh
=> Bump instance type size and switch back to newest containerd

config/userdata-al2023.sh, hack/make-rules/test-e2e-node.sh
copy the existing userdata.sh and switch the `SystemdCgroup` to true for all al2023 CI jobs
=> Ensure we use systemd cgroup with al2023

test/e2e_node/remote/aws/aws_runner.go
/cc @dims @tzneal 
This is the cause of the failure for https://github.com/kubernetes-sigs/kubetest2/pull/234 and https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubetest2/232/pull-kubetest2-aws-node-e2e/1686818508127604736 
Also, it seems the minimum `kubelet-flags` I need to specify is:
```
--test-args='--kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service"'
```
Tests start failing if I omit `--cgroups-per-qos=true --cgroup-root=/` even though it is the default value set in the test kubelet config file.
=> ensure userdata works when image-config file isn't being used

kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/up.go
=> Install aws vpc cni

kubetest2-ec2/config/embed.go, kubetest2-ec2/pkg/deployer/up.go
So we won't need the full repo checked out locally or have to use a remote versions of the files.
=> Embed the configure.sh and ubuntu2204.yaml into the binary

kubetest2-ec2/pkg/deployer/up.go
=> Lookup version when one is NOT specified

kubetest2-ec2/pkg/deployer/dump.go, kubetest2-ec2/pkg/deployer/remote/ssh.go
Also fix some error messages along the way
=> Grab vpc vni related logs

kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go
In prep to switch on AWS external cloud provider
=> Mark the nodes with a cluster id and set hostname / provider id for kubelet

kubetest2-ec2/README.md, kubetest2-ec2/pkg/deployer/dump.go, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/up.go, kubetest2-ec2/pkg/deployer/utils/ec2.go, kubetest2-ec2/pkg/deployer/utils/role.go, kubetest2-ec2/pkg/deployer/utils/s3.go, kubetest2-ec2/pkg/deployer/utils/sshkey.go, kubetest2-ec2/pkg/deployer/utils/ssm.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
Code evolved over a period of time, so trying to clean up to make it easier for supporting it in the longer term.
=> Refactor code to break things apart logically

kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/run-kubeadm.sh, kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/ec2.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
let's gzip the script as it has grown .. to avoid the `User data is limited to 16384 bytes` error
=> Extract shell script from cloud init yaml

kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
https://github.com/kubernetes-sigs/provider-aws-test-infra/issues/137
=> CLI param to enable external AWS cloud provider

kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/run-kubeadm.sh, kubetest2-ec2/pkg/deployer/dump.go
Fun scenario if we don't set it! https://github.com/kubernetes/cloud-provider-aws/issues/656
=> Add node-ip for kubelet and dump all namespaces when wrapping up as well

kubetest2-ec2/config/ubuntu2204.yaml
Do not hard code a specific version, use latest
=> Always use the latest AWS VPC CNI version

.github/workflows/update-deps.yml
Stop creating new branches, reuse the same branch and the same PR if one is pending.
=> Tweak the generated PR from the update-deps github action

hack/build-ami.sh
Reverts kubernetes-sigs/provider-aws-test-infra#228
=> Revert "Drop binary bucket region from url"

kubetest2-ec2/config/al2023.sh
https://github.com/dims/provider-aws-test-infra/pull/new/testing-proposed-updates-to-amazon-eks-ami-pr-1539
=> testing proposed updates to amazon-eks-ami - PR 1539

kubetest2-ec2/config/embed.go, kubetest2-ec2/pkg/deployer/runner.go
example error in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64/1733066790105255936/build-log.txt
=> handle missing ip address(es) better

config/al2023-6.1.yaml, config/ubuntu2204.yaml, kubetest2-ec2/config/ubuntu2204.yaml
=> Keep using containerd 1.7 for now

hack/build-ami.sh, kubetest2-ec2/config/al2023.sh
There are 2 branches now in amazon-eks-ami. the older `master` branch is being deprecated and will be removed. the `main` has a lot of changes. Trying here to make sure this script can work with either branch.
=> support both master and main of amazon-eks-ami

kubetest2-ec2/config/al2023.sh
- if there's a containerd-config.toml (EKS AMI) use that
- append test-handler at the end
- if `nvidia-ctk` is present, then enable `nvidia` runtime
=> Adjust where you pick config.toml from and inject nvidia as well

kubetest2-ec2/config/run-post-install.sh, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go
Just deploys the daemon set. you still need to pass in the correct instance type and worker AMI
see gist - https://gist.github.com/dims/6d3ffbdcdaf2b894e8eb8e7b5c5c3d14
=> Option to deploy nvidia device plugin daemonset

kubetest2-ec2/config/run-post-install.sh
=> Bump CSI driver, Cert Manager, Load Balancer and NVIDIA device plugin versions

config/configure.sh, config/userdata-al2023.sh, config/userdata.sh, kubetest2-ec2/config/configure.sh, kubetest2-ec2/config/run-post-install.sh
=> Use AWS_VPC_K8S_CNI_EXTERNALSNAT - drop AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS

config/userdata-al2023.sh, config/userdata.sh
We still need this for node e2e tests
=> add testnet bridge back

kubetest2-ec2/config/ubuntu2204.yaml
=> Avoid coredns loop by skipping reading etc hosts file - Take 2

kubetest2-ec2/config/run-post-install.sh
=> Do not remove loopback plugin from coredns

kubetest2-ec2/config/al2023.sh, kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/run-post-install.sh
=> set resolv-conf explicitly

kubetest2-ec2/config/al2023.sh
=> Duh fix the chmod params

kubetest2-ec2/config/run-kubeadm.sh
we were picking random cidr from what was reported by the curl for the vpc info. let's pick the correct one corresponding to the ip address of the EC2 instance
=> Pick correct cidr from the VPC

kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/ec2.go
Follow up from https://github.com/aojea/kindnet/issues/46#issuecomment-2243935615
Slack conversation:
https://kubernetes.slack.com/archives/C09QZ4DQB/p1721676080487939?thread_ts=1721127300.133689&cid=C09QZ4DQB
=> Pick and specify a subnet/CIDR to start all the instances

kubetest2-ec2/config/al2023.sh
xref: https://github.com/kubernetes-sigs/provider-aws-test-infra/issues/361
=> Check s3 file metadata to ensure it is completely updated

config/al2023-6.1.yaml, config/ubuntu2204.yaml, kubetest2-ec2/config/ubuntu2204.yaml
xref: https://github.com/kubernetes/kubernetes/issues/128612
=> Stick to containerd 1.7 environment

hack/build-ami.sh
=> Add an instance profile for packer

vendor/k8s.io/apimachinery/pkg/api/operation/operation.go, vendor/k8s.io/apimachinery/pkg/runtime/scheme.go, vendor/k8s.io/kubernetes/pkg/features/kube_features.go, vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go, vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/external-snapshotter/volume-group-snapshots/csi-hostpath-plugin.yaml, vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/gce-pd/node_ds.yaml, vendor/k8s.io/kubernetes/test/e2e/testing-manifests/storage-csi/mock/csi-mock-proxy.yaml, vendor/modules.txt
PR filed with output of running hack/bump-k8s.sh on Date: 03/05/2025
=> Bump Kubernetes on (03/05/2025)

vendor/k8s.io/apiserver/pkg/endpoints/request/webhook_duration.go, vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
PR filed with output of running hack/bump-k8s.sh on Date: 03/07/2025
=> Bump Kubernetes on (03/07/2025)

kubetest2-ec2/config/run-post-install.sh
Trying to fix flakes:
https://github.com/kubernetes/kubernetes/issues/131071
=> Bump vpc-cni settings to avoid ip allocation failures

hack/build-ami.sh
the old sed will not work as the script has changed:
https://github.com/awslabs/amazon-eks-ami/commit/763cb21761bda27ac75c184fa9b0a3e507254968
=> adapt to change in install-worker.sh

vendor/k8s.io/apimachinery/pkg/api/operation/operation.go, vendor/k8s.io/apimachinery/pkg/api/validate/immutable.go, vendor/k8s.io/apimachinery/pkg/runtime/scheme.go, vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go, vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go, vendor/k8s.io/apiserver/pkg/cel/common/valuesunstructured.go, vendor/k8s.io/client-go/openapi/client.go, vendor/k8s.io/client-go/pkg/version/base.go, vendor/k8s.io/client-go/rest/request.go, vendor/k8s.io/component-base/version/base.go, vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go, vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.validations.go, vendor/k8s.io/kubernetes/test/e2e/testing-manifests/kubectl/agnhost-primary-pod.yaml, vendor/k8s.io/kubernetes/test/e2e_node/remote/utils.go, vendor/k8s.io/kubernetes/test/utils/image/manifest.go
PR filed with output of running hack/bump-k8s.sh on Date: 05/07/2025
=> Bump Kubernetes on (05/07/2025)

vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go, vendor/k8s.io/apiserver/pkg/audit/request.go
PR filed with output of running hack/bump-k8s.sh on Date: 05/13/2025
=> Bump Kubernetes on (05/13/2025)

vendor/k8s.io/kubernetes/test/utils/image/manifest.go
PR filed with output of running hack/bump-k8s.sh on Date: 08/15/2025
=> Bump Kubernetes on (08/15/2025)

vendor/k8s.io/apimachinery/pkg/api/resource/quantity_proto.go, vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/collections.go, vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/protobuf.go, vendor/k8s.io/apimachinery/pkg/runtime/types_proto.go, vendor/k8s.io/apimachinery/pkg/util/sets/set.go, vendor/k8s.io/kubernetes/test/utils/image/manifest.go
PR filed with output of running hack/bump-k8s.sh on Date: 09/25/2025
=> Bump Kubernetes on (09/25/2025)
