config/aws-instance.yaml, config/configure.sh, config/ubuntu2204.yaml
=> Ubuntu 2204 Instance config

config/ubuntu2204.yaml
@upodroid - would this be enough to avoid having multiple SSH_USER (one for each image)? Let's just standardize on one for all of the images on aws.
examples of this:
- https://alestic.com/2014/01/ec2-change-username/
- https://cloudinit.readthedocs.io/en/latest/reference/examples.html
=> switch default user id for ubuntu image

config/configure.sh
the amazon AMI(s) have switched off the systemd based cgroups. let's do the same for ubuntu as well.
=> Force the old style cgroup non systemd

config/ubuntu2204.yaml
by default the ec2-user is not in a group that allows them access to containerd.sock, to keep it simple add that user to the `root` group
=> Add ec2-user to root group to allow access to containerd.sock

hack/make-rules/test-e2e-node.sh
Reverts kubernetes-sigs/provider-aws-test-infra#10
I forgot I can specify a `path_alias` in the prowjob :(
```
maha4472@knative-e2e:~/provider-aws-test-infra$ grep -r KubeletCredentialProviders .
./vendor/k8s.io/kubernetes/test/e2e_node/remote/node_e2e.go:	featureGateFlag := "--kubelet-flags=--feature-gates=DisableKubeletCloudCredentialProviders=true,KubeletCredentialProviders=true"
./vendor/k8s.io/kubernetes/pkg/features/kube_features.go:	KubeletCredentialProviders featuregate.Feature = "KubeletCredentialProviders"
./vendor/k8s.io/kubernetes/pkg/features/kube_features.go:	KubeletCredentialProviders: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.28
```
```
REDACTED@knative-e2e:~/go/src/sigs.k8s.io/provider-aws-test-infra$ go mod tidy …
```
=> Revert "Fix k/k path"

hack/make-rules/test-e2e-node.sh
Drop the `aws ec2 authorize-security-group-ingress` we were trying, we don't need it.
/assign @upodroid
=> Drop Temporary SG hack for aws ec2 authorize-security-group-ingress

config/aws-instance-arm64.yaml, config/configure.sh
drop the eks version of images and keep the base ubuntu + al2023
=> Adding configuration for arm64 based CI jobs

hack/make-rules/test-e2e-node.sh
- We should not be prepulling images in node e2e jobs
- A slightly higher timeout as well
=> Add better defaults for arm64/e2e-node ci jobs

test/e2e_node/remote/aws/aws_runner.go
If we don't, we end up with a small root disk. the current hard coded default is for a AL2/2023 AMI
=> Lookup root device name for AMI

hack/make-rules/test-e2e-node.sh
Currently this is 45 mins and that is not enough especially for serial tests:
https://github.com/kubernetes/kubernetes/blob/6dbb1c6cf074872ac39485b07b9bd3106654ae3a/test/e2e_node/remote/remote.go#L34
=> Default to 4 hours of test timeout

config/ubuntu2204.yaml
See https://github.com/kubernetes/kubernetes/issues/102818
=> Graceful node shutdown conflicts with unattended-upgrades package

Makefile, hack/make-rules/test-e2e-node.sh, test/e2e_node/remote/aws/aws_runner.go
Merging https://github.com/kubernetes-sigs/kubetest2/pull/230 will allow us to use kubetest2 for both EC2 and GCE node e2e tests with simplified prowjob generator logic.
/cc @dims
=> Add kubetest2 support

config/ubuntu2204.yaml
https://cs.k8s.io/?q=nfs&i=nope&files=.*mirror_pod_test.go&excludeFiles=&repos=
Errors looks like these:
```
Jun 29 17:35:33.680: INFO: At 2023-06-29 17:33:28 +0000 UTC - event for static-pod-nfs-test-pod03241026-a521-42ee-825d-2a6ece0586c0-i-0cff3de3e6ff915b7: {kubelet i-0cff3de3e6ff915b7} FailedMount: MountVolume.SetUp failed for volume "nfs-vol" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 10.100.0.119:/exports /var/lib/kubelet/pods/aefc5e225fd23cb971c5db6b5d339959/volumes/kubernetes.io~nfs/nfs-vol
Output: mount: /var/lib/kubelet/pods/aefc5e225fd23cb971c5db6b5d339959/volumes/kubernetes.io~nfs/nfs-vol: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```
=> install nfs-common package as a e2e node test is mounting an nfs server

.github/workflows/update-deps.yml, hack/bump-k8s.sh
Since we are vendoring k/k, let's make sure we update it periodically. There's a script that automates the dependency update and a GH action opens a PR with the changes.
=> Add a GitHub action to update kubernetes periodically

hack/build-ami.sh, hack/bump-k8s.sh, hack/make-rules/test-e2e-node.sh, hack/populate-s3.sh
Threading it all together
- build ami straight from main branch of amazon-eks-ami
- but using k8s binaries we push to our own s3 bucket
- avoid rebuilding the AMI more than once a day
- ensure scripts fail fast
- avoid tripping over the variable names across scripts
=> Build EKS AMI and then run node e2e tests using that new AMI

hack/build-ami.sh
Same as in https://github.com/awslabs/amazon-eks-ami/blob/8d68370eff9a30573d8e8da91903c7ca5376fa01/Makefile#L34
=> Default arch is amd64 when building eks image

config/userdata-al2023.sh
This shouldn't be needed since AL2023 has systemd 252.
=> remove the systemd hack on al2023

hack/bump-k8s.sh
current failure before this PR was:
```
+ go get k8s.io/kubernetes@HEAD
go: k8s.io/kubernetes@HEAD: invalid version: reading https://proxy.golang.org/k8s.io/kubernetes/@v/%21h%21e%21a%21d.info: 404 Not Found
server response: not found: fetch timed out
```
=> Trying to fix update dependencies action

hack/make-rules/test-e2e-node.sh
This change is designed to work with kubetest2 changes.
Right now, an image config file that looks like this is required:
```yaml
images:
al2023-6-1:
ssm_path: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
instance_type: m6g.large
user_data_file: al2023-6.1.yaml
ubuntu-2204:
ssm_path: /aws/service/canonical/ubuntu/server/jammy/stable/current/arm64/hvm/ebs-gp2/ami-id
instance_type: m6g.large
user_data_file: ubuntu2204.yaml
```
This is quite burdensome and I'm proposing the following changes:
Pass everything required as flags to kubetest2 so the generator I'm writing can work easily. kops configures all their various mutations by various flags being passed to kubetest2.
For example, to run ubuntu2204 tests, all I would do is pass two different for values for the …
=> Run e2e tests without specifying an image config file

config/userdata-al2023.sh
Tests assume that containerd cgroup will be at
/system.slice/containerd.service not /runtime.slice/containerd.service
Should fix https://github.com/kubernetes/kubernetes/issues/119585
=> remove the runtime.slice configuration

kubetest2-ec2/pkg/deployer/utils/source.go
some of the operations may end up with `./hack/print-workspace-status.sh` returning version with `-dirty` in it, indicating that an extra modification to one of the files is present or the git workspace is not pristine enough (extra file?). just ignore those for now. (see example below)
```
[40915:40912 - 0:2038] 09:02:34 [davanum@c889f3bd53ed:o +1] ~/go/src/k8s.io/kubernetes
$ touch a.txt
[40915:40912 - 0:2039] 03:27:00 [davanum@c889f3bd53ed:o +1] ~/go/src/k8s.io/kubernetes
$ hack/print-workspace-status.sh
STABLE_BUILD_GIT_COMMIT f4041204c0029374be6949164c6f184e27408f7e
STABLE_BUILD_SCM_STATUS dirty
STABLE_BUILD_SCM_REVISION v1.29.0-alpha.0.40+f4041204c00293-dirty
STABLE_BUILD_MAJOR_VERSION 1
STABLE_BUILD_MINOR_VERSION 29+
STABLE_DOCKER_TAG v1.29.0-alpha.0.40_f4041204c00293-dirty …
```
=> Drop the dirty suffix in version number

config/configure.sh
```
Warning  FailedCreatePodSandBox  10m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "715301634ac099a9643293f42cffa758b4faa9c16600bc800be1d626f9ae610e": plugin type="aws-cni" name="aws-cni" failed (add): failed to find plugin "aws-cni" in path [/home/containerd/opt/cni/bin]
```
=> use the usual directory for CNI as AWS VPC CNI does not like alternate directories

kubetest2-ec2/config/ubuntu2204.yaml
xref:
- https://github.com/aws/amazon-vpc-cni-k8s/pull/2161/commits/ceacdb9ee02f6945070665770165b138a1125ae7
- original issue from kops folks : https://github.com/aws/amazon-vpc-cni-k8s/issues/2103
- Looks like https://github.com/aws/amazon-vpc-cni-k8s/pull/2118 still has to land
thanks @tzneal @jdn5126 @jayanthvn for debugging and tips!
```
systemd-udev - Linux distributions that install the systemd-udev package create /usr/lib/systemd/network/99-default.link with Link.MACAddressPolicy set to persistent. This policy may cause the MAC address assigned to the host veth interface for a pod to change after the interface is moved to the host network namespace. The CNI plugin installs a static ARP binding for the default gateway in the pod network namespace pointing to the host veth MAC, so …
```
=> Switch back to aws vpc cni - Revert systemd-udev change (MACAddressPolicy)  that disables networking from pods

kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/up.go
We need larger instance types for running more pods. Let's not constrict ourselves right now. 
Also more pods, needs more ENI(s), especially for AWS VPC CNI, or we run into `ContainerCreating` issue where pods are stuck. Context:
- https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md
- https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/eni-and-ip-target.md
- https://webera.blog/eks-aws-default-vpc-cni-tuning-for-small-networks-a81cbfc48549
- https://github.com/aws/aws-eks-best-practices/blob/master/content/networking/vpc-cni/index.md
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html
=> Instance types are way too small

hack/build-ami.sh, hack/make-rules/test-e2e-node.sh
We may be running CI jobs in parallel and a couple of them may end up trying to build the same image at the same time and trip over each other. So even if `make k8s` fails, check if the ami is present because that's what we need to continue.
=> check for ami image again just before make k8s

config/aws-instance-eks.yaml, config/userdata.sh, test/e2e_node/remote/aws/aws_runner.go
the version of systemd-run in EKS images do not support `-E` added here:
https://github.com/kubernetes/kubernetes/commit/ad7b9b56f5b2eabd6fa2de0446bcf8f858722e4d#diff-39ac8bcd746449ace559f6d09bd16a43bf207323181481899f906adb55b03c6fR253
- Also bump time we wait for things to come up
- Bump to newer EKS images
=> tolerate -E vs --setenv for systemd-run command

kubetest2-ec2/config/al2.sh, kubetest2-ec2/config/run-kubeadm.sh, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/up.go, kubetest2-ec2/pkg/deployer/utils/random.go
Tested by hand using:
```
go install . && kubetest2 ec2 \
--build \
--target-build-arch linux/amd64 \
--stage provider-aws-test-infra-dims \
--worker-image ami-0e0b0f2cb811d16b0 \
--num-nodes 1 \
--worker-user-data-file config/al2.sh \
--up \
--test=ginkgo \
-- \
--use-built-binaries true \
--focus-regex='should get a host IP'
```
=> Add support to run al2 worker nodes

hack/populate-s3.sh, kubetest2-ec2/config/al2023.sh
fix a typo in populate-s3.sh as well
tested by hand using:
```
go install . && kubetest2 ec2 \
--build \
--target-build-arch linux/amd64 \
--stage provider-aws-test-infra-dims-west-2 \
--worker-image ami-0272ac35db54e22cb \
--region us-west-2 \
--num-nodes 1 \
--worker-user-data-file config/al2023.sh \
--up \
--test=ginkgo \
-- \
--use-built-binaries true \
--focus-regex='should get a host IP'
```
NOTES:
- containerd needs to be explicitly started
- Get instance metadata needs a token -  https://medium.com/@sumitkumar.it81/get-instance-metadata-in-amazon-linux-2023-al2023-e4bf0611d0ad
=> Add support for AL2023 EKS images

kubetest2-ec2/config/al2023.sh
Looks like containerd defaults to `SystemdCgroup = false`, we can just reuse the /etc/eks/containerd/containerd-config.toml which is already setup correctly
=> Use systemd cgroup driver

kubetest2-ec2/config/al2023.sh
print the versions too so it's easy to figure out when things fail.
=> Force a reinstall of containerd and runc

kubetest2-ec2/config/ubuntu2204.yaml
NFS tests have been failing because the `mount.nfs` helper is missing:
```
Nov 30 23:25:44.020: INFO: At 2023-11-30 23:10:47 +0000 UTC - event for pvc-volume-tester-writer-4khdp: {kubelet ip-172-31-25-49.ec2.internal} FailedMount: MountVolume.SetUp failed for volume "pvc-3057a841-83d6-4fe1-a5c3-30eadb40c235" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o relatime,vers=4.1 172.31.26.195:/export/pvc-3057a841-83d6-4fe1-a5c3-30eadb40c235 /var/lib/kubelet/pods/2912148a-e10d-4d0f-80cb-56ab36409961/volumes/kubernetes.io~nfs/pvc-3057a841-83d6-4fe1-a5c3-30eadb40c235
Output: mount: /var/lib/kubelet/pods/2912148a-e10d-4d0f-80cb-56ab36409961/volumes/kubernetes.io~nfs/pvc-3057a841-83d6-4fe1-a5c3-30eadb40c235: bad option; for several filesystems (e.g. nfs, cifs) …
```
=> Add rpcbind back, for nfs

kubetest2-ec2/pkg/deployer/runner.go
The 1.x AWS SDK for go does not enable the full credential chain by default (see `Sessions options from Shared Config` here: https://docs.aws.amazon.com/sdk-for-go/api/aws/session/). Most AWS SDKs do this by default -- the 2.x go SDK does.
This allows usage of credential helpers and `~/.aws/config` profiles without setting additional environment variables; much more convenient for hacking around 😄
=> Enable full AWS SDK credential chain

kubetest2-ec2/pkg/deployer/deployer.go
- https://aws.amazon.com/ec2/instance-types/r7g/
- https://aws.amazon.com/ec2/instance-types/r5/
```
Instance Size  vCPU  Memory (GiB)  Instance Storage (GB)  Networking Performance (Gbps)  EBS Bandwidth (Mbps)
r5d.4xlarge     16      128          2 x 300 NVMe SSD        Up to 10                       4,750
Instance Size  vCPU  Memory (GiB)  Instance Storage (GB)  Network Bandwidth (Gbps)      EBS Bandwidth (Gbps)
r7gd.4xlarge    16      128          1 x 950 NVMe SSD        Up to 15                       Up to 10
```
=> switch arm64 instance type to more closely match the amd64 one

config/al2023-6.1.yaml, config/ubuntu2204.yaml, kubetest2-ec2/config/ubuntu2204.yaml
Snippet from:
```
Feb 07 13:36:48.024915 bootstrap-e2e-master containerd[1191]: time="2024-02-07T13:36:48.024858788Z" level=error msg="PullImage \"registry.k8s.io/kube-apiserver-amd64:v1.30.0-alpha.1.107_052bce26f4f48b\" failed" error="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver-amd64:v1.30.0-alpha.1.107_052bce26f4f48b\": failed to resolve reference \"registry.k8s.io/kube-apiserver-amd64:v1.30.0-alpha.1.107_052bce26f4f48b\": registry.k8s.io/kube-apiserver-amd64:v1.30.0-alpha.1.107_052bce26f4f48b: not found"
```
Discussion thread:
https://cloud-native.slack.com/archives/GGEQHJ0AE/p1707284414739809?thread_ts=1707230141.026879&cid=GGEQHJ0AE
containerd PR that just merged:
https://github.com/containerd/containerd/pull/9779
artifacts got …
=> Switch back to containerd 2.x.x

hack/build-ami.sh
found https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-slow/1755388885224919040/build-log.txt
```
2024-02-08T00:46:42Z:     amazon-ebs: Last metadata expiration check: 0:00:36 ago on Thu Feb  8 00:46:06 2024.
2024-02-08T00:46:42Z:     amazon-ebs: No match for argument: [1mcri-tools(B[m
2024-02-08T00:46:42Z:     amazon-ebs: Error: Unable to find a match: cri-tools
2024-02-08T00:46:42Z: ==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
2024-02-08T00:46:42Z: ==> amazon-ebs: Terminating the source AWS instance...
```
=> drop cri-tools

hack/build-ami.sh
note above from https://github.com/awslabs/amazon-eks-ami/blob/master/README.md
=> Try main branch of amazon-eks-ami ahead of the switch

config/userdata-al2023.sh, config/userdata.sh
newer EKS ami image does not come with extra bits we relied on before.
=> inject config.toml directly

kubetest2-ec2/config/configure.sh, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
`pull-containerd-node-e2e` is for running node e2e tests against containerd. we need something similar to run other tests in k/k as well against containerd master. this is the first step. being able to construct and use a url to download and run a containerd built from the PR pull refs
=> Support running presubmits against containerd repository

kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go
We'll need these to model jobs like `ci-kubernetes-e2e-gci-gce-alpha-enabled-default` and `ci-kubernetes-e2e-gci-gce-alpha-features`
https://cs.k8s.io/?q=name%3A%20ci-kubernetes-e2e-gci-gce-alpha&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra
=> Add support for `runtime-config` and `feature-gates` for apiserver

config/userdata-al2023.sh, config/userdata.sh, kubetest2-ec2/config/al2023.sh, kubetest2-ec2/config/ubuntu2204.yaml
Related to https://github.com/kubernetes/kubernetes/issues/126089
copied the masquerading related iptables entries from k/k repo:
https://cs.k8s.io/?q=iptables&i=nope&files=cluster%2Fgce%2Fgci%2Fconfigure-helper.sh&excludeFiles=&repos=kubernetes/kubernetes
=> Add rules for ip masquerade

config/ubuntu2204.yaml
```
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.11.1
linux/arm64, go1.20.7, ae2bbc2
[FATAL] plugin/loop: Loop (172.31.0.2:60606 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 1723865833739751426.5954253132454464401."
ENDLOG for container kube-system:coredns-5cfdc65f69-2cc4l:coredns
[FAILED] Error waiting for all pods to be running and ready: Timed out after 600.000s.
```
=> Avoid coredns loop by skipping reading etc hosts file

kubetest2-ec2/pkg/deployer/utils/ec2.go
for example from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-alpha-enabled-default/1816085067617800192/build-log.txt
```
I0724 12:19:56.394868    3311 dump.go:30] copying logs to /logs/artifacts/logs
Error: unable to launch instance : creating instance, Unsupported: Your requested instance type (r5d.xlarge) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f.
status code: 400, request id: 49ab3728-497e-4946-b9fb-e89135785cd3
```
this started happening since we are now picking a subnet (earlier we left to chance!)
=> Skip us-east-1e for now

kubetest2-ec2/pkg/deployer/runner.go
Would be nice to have a log message before dialing ssh, so that it is more clear that there is some network/ACL issue blocking cluster up in the case of misconfiguration. 
Feel free to close issue if no longer relevant due to #352. 
Thanks!
Example default logs post this change:
```
I0726 14:42:41.244968 4090793 ec2.go:149] Randomly picked subnet ID: subnet-023a4c75427d3819d
I0726 14:42:47.786442 4090793 runner.go:602] launched new instance i-0f102a247f3296f85 with ami-id: ami-013b3de8a8fa9b39f on instance type: r5d.xlarge
I0726 14:42:47.786469 4090793 up.go:139] started instance id: i-0f102a247f3296f85
I0726 14:42:47.786519 4090793 runner.go:228] waiting for i-0f102a247f3296f85 to start (5 mins)
I0726 14:42:48.338819 4090793 runner.go:274] instance-connect flag is set, using ec2 instance …
```
=> Add more logging for kubetest2-ec2 assignNewSSHKey

kubetest2-ec2/config/al2023.sh, kubetest2-ec2/config/run-kubeadm.sh, kubetest2-ec2/pkg/deployer/build.go, kubetest2-ec2/pkg/deployer/build/options.go, kubetest2-ec2/pkg/deployer/build/stage.go, kubetest2-ec2/pkg/deployer/deployer.go, kubetest2-ec2/pkg/deployer/runner.go
Still trying to track down where things go wrong:
recent log https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-ec2-eks-conformance-latest/1820638086200037376/artifacts/logs/i-0b01c40156ccab6d4/cloud-init-output.log
```
download: s3://provider-aws-test-infra/v1.32.0-alpha.0.18+00236ae0d73d24/kubernetes-server-linux-amd64.tar.gz to ./kubernetes-server-linux-amd64.tar.gz
+ tar -xvzf kubernetes-server-linux-amd64.tar.gz
kubernetes/
kubernetes/server/
kubernetes/server/bin/
kubernetes/server/bin/kube-apiserver
kubernetes/server/bin/kube-controller-manager
kubernetes/server/bin/kube-scheduler
kubernetes/server/bin/kube-proxy
kubernetes/server/bin/kubectl
kubernetes/server/bin/kubectl.tar
kubernetes/server/bin/kubectl.docker_tag
kubernetes/server/bin/kube-scheduler.tar
gzip: …
```
=> Upload to a temp location based on run id and then switch it the actual location

kubetest2-ec2/config/al2023.sh, kubetest2-ec2/config/kubeadm-init.yaml, kubetest2-ec2/config/kubeadm-join.yaml, kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
This PR adds the runtime.slice and makes use of it as recommended in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/).
=> Setup runtime.slice for containerd/kubelet

kubetest2-ec2/config/embed.go, kubetest2-ec2/config/ubuntu/10-kubeadm.conf, kubetest2-ec2/config/ubuntu/containerd-installation.service, kubetest2-ec2/config/ubuntu/containerd.service, kubetest2-ec2/config/ubuntu/containerd.target, kubetest2-ec2/config/ubuntu/credential-provider.yaml, kubetest2-ec2/config/ubuntu/kubelet.service, kubetest2-ec2/config/ubuntu2204.yaml, kubetest2-ec2/pkg/deployer/runner.go, kubetest2-ec2/pkg/deployer/utils/userdata.go
Enables us to pass in the gzip/base64 encoded version of the files into cloud init yaml
=> Move embedded files outside the cloud init yaml

config/configure.sh, kubetest2-ec2/config/configure.sh
We are building arm64 tgz(s) for 1.7/2.0 and main branches of containerd:
- https://github.com/kubernetes/test-infra/pull/33771
- https://github.com/kubernetes/test-infra/pull/33774
Unfortunately there's a typo `-` vs `.` in the file name which is being rectified in:
- https://github.com/containerd/containerd/pull/10964
- https://github.com/containerd/containerd/pull/10967
- https://github.com/containerd/containerd/pull/10968
So until everything lands have a mitigation in place here to try both url(s).
=> Download arm64 binaries from GCS bucket as well

config/al2023-6.1.yaml, config/ubuntu2204.yaml, kubetest2-ec2/config/ubuntu2204.yaml
Reverts kubernetes-sigs/provider-aws-test-infra#382
with https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/385 and the PRs linked from there, we should be all set to go back to `main`
=> Revert "Stick to containerd 1.7 environment"

hack/build-ami.sh
avoids needing to fetch the container from ecr:
https://github.com/awslabs/amazon-eks-ami/blob/main/templates/shared/runtime/bin/cache-pause-container#L20-L22
=> use community pause container

config/userdata-al2023.sh, config/userdata.sh, kubetest2-ec2/config/al2023.sh
Mimic https://github.com/kubernetes/test-infra/pull/34013.
CDI tests are failing on containerd jobs.
https://testgrid.k8s.io/sig-node-ec2
This hopefully should fix this.
=> enable cdi for aws containerd jobs

kubetest2-ec2/config/kubeadm-init.yaml
the cloud provider flag is deprecated and also removed from the apiserver flag options. https://github.com/kubernetes/kubernetes/pull/130162
=> Remove the deprecated cloud provider flag for apiserver

vendor/k8s.io/kubernetes/test/e2e_node/builder/build.go
Builds seems to be picking up git information from this repo instead of the k8s repo. So set the directory explicitly.
=> cd to k8sRoot before running script

config/configure.sh, kubetest2-ec2/config/configure.sh
Fix for https://github.com/kubernetes/test-infra/pull/34510
Apparently some of the node test scenarios require `runc` to be present in PATH as well.
Please see https://github.com/containerd/containerd/pull/11557 for traffic
=> copy `runc` binary to $PATH

config/aws-instance-arm64.yaml, config/aws-instance.yaml, kubetest2-ec2/pkg/deployer/runner.go
We need to downgrade from `6.8.0-1025-aws` to `6.8.0-1024-aws`
Fix for failures mentioned in : https://github.com/kubernetes/kubernetes/issues/131094
Related to those already talked about in : https://github.com/kubernetes/kubernetes/issues/129280
Related to the upstream ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/linux-aws/+bug/2101914
Let's see if we can revive this CI job:
https://testgrid.k8s.io/amazon-ec2#ci-cloud-provider-aws-e2e-kubetest2&width=20
```
❯ aws ssm get-parameters --names \
/aws/service/canonical/ubuntu/server/24.04/stable/20250305/amd64/hvm/ebs-gp3/ami-id \
--query 'Parameters[0].[Value]' --output text
ami-075686beab831bb7f
```
=> pin to a older ubuntu 24.04 kernel

vendor/k8s.io/apiserver/pkg/features/kube_features.go, vendor/k8s.io/kubernetes/pkg/features/kube_features.go
PR filed with output of running hack/bump-k8s.sh on Date: 04/21/2025
=> Bump Kubernetes on (04/21/2025)

hack/build-ami.sh
compensate for https://github.com/awslabs/amazon-eks-ami/pull/2235
the 2.x packages are not yet public in repositories. latest is still 1.7.x.
=> force containerd 1.7 for now in AL2/AL2023 builds

hack/build-ami.sh
missed 2 spots in https://github.com/kubernetes-sigs/provider-aws-test-infra/commit/f8f605ae10ab86bdc63a004b73953df6d4d6af4f
=> force containerd 1.7 for now in AL2/AL2023 builds - take 2
